apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mysql-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-mysql-app
  template:
    metadata:
      labels:
        app: flask-mysql-app
    spec:
      containers:
      - name: flask-mysql-app
        image: asia-southeast2-docker.pkg.dev/bespin-sandbox/flask-mysql/flask-mysql-app:1.0
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "10.1.10.14"   # IP Private/Public VM MySQL kamu
        - name: DB_NAME
          value: "testdb"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASS
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: flask-mysql-app
spec:
  type: LoadBalancer
  selector:
    app: flask-mysql-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000