apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mysql-app
  labels:
    app: flask-mysql-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-mysql-app
  template:
    metadata:
      labels:
        app: flask-mysql-app
    spec:
      containers:
      - name: flask
        image: asia-southeast2-docker.pkg.dev/bespin-sandbox/flask-mysql/flask-mysql-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-mysql-service
  labels:
    app: flask-mysql-app
spec:
  type: LoadBalancer
  selector:
    app: flask-mysql-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
